### ISSUE TITLE
Release notes for 1.18.0

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/dbm#195]
**Release time**

`2022-06-10`

**Components involved**

- ClickHouse
- Trino & Presto
- MySQL

**Check list**

#### General

---

- [x] Split multiple data sources and configure them as separate components
- [x] Support tray function
- [x] Fix the exception of Presto using quick query
- [x] Support metadata host filtering
- [x] Support query history reference to the editor
- [x] Fix the error message that the query history cannot be viewed

#### ClickHouse

---

- [x] Support specifying a database when building a data source

#### Trino & Presto

---

- [x] Support specifying a database and catalog when building a data source #158 
- [x] Support metadata source management Trino & Presto service information #158 
- [x] Support metadata source management Trino & Presto create database #158

#### MySQL

---

- [x] Support MySQL (custom query and data source management) #180
- [x] Add MySQL docs #180

**Comment by qianmoQ** [comment]
Released
