### ISSUE TITLE
Release notes for 1.19.0

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/dbm#208]
**Release time**

`2022-06-23`

**Components involved**

- ClickHouse
- Trino & Presto
- MySQL
- PostgreSQL

**Check list**

#### ClickHouse

---

- [ ] Support the currently stopped running process

#### Trino & Presto

---

- [ ] Supports query result time and total number of data [issues-158](https://github.com/EdurtIO/dbm/issues/158)

#### MySQL

---

- [ ] Support quick query operation [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [ ] Supports query result time and total number of data [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [ ] Supports monitor → processors [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [ ] Supports monitor → connection [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [ ] Supports metadata management of disk usage [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [ ] Support metadata management menu server related operations [issues-180](https://github.com/EdurtIO/dbm/issues/180)

#### PostgreSQL

---

- [ ] Support PostgreSQL (custom query and data source management)
