### ISSUE TITLE
Release notes for 1.22.0

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/dbm#259]
**Release time**

`2022-08-12`

**Components involved**

- ClickHouse
- MySQL
- PostgreSQL
- Apache Druid
- ElasticSearch
- Hologres

**Check list**

#### General

---

- [x] Rebuild the table configuration layout
- [x] Fix the query result is not displayed in the column data under certain circumstances
- [x] Optimize the display type icon of the data source list

#### Editor

---

- [x] Support the new editor to delete the data table shortcut menu (new editor)
- [x] Display and query additional information (new editor)

#### ClickHouse

---

- [x] Support `MySQL` table engine
- [x] Support `Hive` table engine
- [x] Support `PostgreSQL` database engine
- [x] Support https protocol [issues-247](https://github.com/EdurtIO/dbm/issues/247)

#### MySQL

---

- [x] Support metadata management, build a database, specify character sets & collation [issues-180](https://github.com/EdurtIO/dbm/issues/180)
- [x] Fix only_full_group_by could not obtain metadata [issues-180](https://github.com/EdurtIO/dbm/issues/180)

#### PostgreSQL

---

- [x] Fix the exception of the metadata management build table
- [x] Support rename database
- [x] Fix failure to query when database is empty

#### Apache Druid

---

- [x] Support quick query

#### ElasticSearch

---

- [x] Support ElasticSearch (query and data source management)

#### Hologres

---

- [x] Support Hologres (query and data source management)

**Comment by qianmoQ** [comment]
Released
